apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: 869935103158.dkr.ecr.us-west-2.amazonaws.com/zm-mle-k8s-images:zm-gateway-002
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 9696 
        env:
          - name: TF_SERVING_HOST 
            value: tf-serving-clothing-model.default.svc.cluster.local:8500
