version: "3.9"
services:
  clothing-model:
    image: zm-model:xception-v4-001
  gateway: 
    image: zm-gateway:002
    environment:
      - TF_SERVING_HOST=clothing-model:8500
    ports:
      - "9696:9696"

